### ISSUE TITLE
"last_message_recived" property should be "last_message_received"

### ISSUE THREAD

**Issue by Nzbuu** [witnessmenow/Universal-Arduino-Telegram-Bot#11]
There's a spelling mistake in the UniversalTelegramBot API. I can fix it but that will affect break existing programmes that use it. What do you prefer?

**Comment by witnessmenow** [comment]
Darn my spelling strikes again! Thanks for pointing it out.

I think it would be good to fix, it will fail to compile for people who update and still have old code but hopefully its easy enough to find.I guess the earlier it's fixed the less people it will impact. 

If you would like to submit a pull request making this change (including updating the examples) that would be awesome! I can pick it up at some stage if you can't though

**Comment by witnessmenow** [comment]
Closed by #12 pull request which has been merged
