### ISSUE TITLE
Cant send massage out of Timer

### ISSUE THREAD

**Issue by windiesel** [witnessmenow/Universal-Arduino-Telegram-Bot#115]
I made a timer (every 10s) and tried to send a massage with it, but got a reset.
Finally I set a flag in with the timer and used loop to send the massage. -worked perfect.
It might be an issue of my programming skills, 
best regards.

**Comment by witnessmenow** [comment]
Timer may not have access to Wifi or some other piece of memory needed. I'm not too familiar with them. Not really anything I can do from the library point of view
