### ISSUE TITLE
bot.getUpdates() always returns 0 with ESP8266

### ISSUE THREAD

**Issue by RiccardoBonesi** [witnessmenow/Universal-Arduino-Telegram-Bot#121]
I tryed the "FlashLED" example for ESP8266 and I just replaced the ssid, password and BOTtoken. 
It connects to the wifi but when I send a message to the bot via telegram `bot.last_message_received` and `numNewMessages` are always `0`

**Comment by witnessmenow** [comment]
try adding "client.setInsecure();" to your setup

**Comment by RiccardoBonesi** [comment]
Thank you, this worked!
