### ISSUE TITLE
Exit 1 Status Error Compiling 

### ISSUE THREAD

**Issue by nerissaong** [witnessmenow/Universal-Arduino-Telegram-Bot#137]
hello, i coding the Flash LED for the ESP32 (Wemos LoLin32) and i met with this error please help urgent!

Arduino: 1.8.11 (Windows 10), Board: "WEMOS LOLIN32, 80MHz, Default, 240MHz (WiFi/BT), 921600"

C:\Users\User\Documents\Arduino\libraries\UniversalTelegramBot\src\UniversalTelegramBot.cpp:319:11: error: DynamicJsonBuffer is a class from ArduinoJson 5. Please see arduinojson.org/upgrade to learn how to upgrade your program to ArduinoJson version 6

   DynamicJsonBuffer jsonBuffer;

           ^

C:\Users\User\Documents\Arduino\libraries\UniversalTelegramBot\src\UniversalTelegramBot.cpp:369:11: error: DynamicJsonBuffer is a class from ArduinoJson 5. Please see arduinojson.org/upgrade to learn how to upgrade your program to ArduinoJson version 6

     DynamicJsonBuffer jsonBuffer;

           ^

C:\Users\User\Documents\Arduino\libraries\UniversalTelegramBot\src\UniversalTelegramBot.cpp:530:11: error: DynamicJsonBuffer is a class from ArduinoJson 5. Please see arduinojson.org/upgrade to learn how to upgrade your program to ArduinoJson version 6

   DynamicJsonBuffer jsonBuffer;

           ^

C:\Users\User\Documents\Arduino\libraries\UniversalTelegramBot\src\UniversalTelegramBot.cpp:547:11: error: DynamicJsonBuffer is a class from ArduinoJson 5. Please see arduinojson.org/upgrade to learn how to upgrade your program to ArduinoJson version 6

   DynamicJsonBuffer jsonBuffer;

           ^

C:\Users\User\Documents\Arduino\libraries\UniversalTelegramBot\src\UniversalTelegramBot.cpp:564:11: error: DynamicJsonBuffer is a class from ArduinoJson 5. Please see arduinojson.org/upgrade to learn how to upgrade your program to ArduinoJson version 6

   DynamicJsonBuffer keyboardBuffer;

           ^

C:\Users\User\Documents\Arduino\libraries\UniversalTelegramBot\src\UniversalTelegramBot.cpp:589:11: error: DynamicJsonBuffer is a class from ArduinoJson 5. Please see arduinojson.org/upgrade to learn how to upgrade your program to ArduinoJson version 6

   DynamicJsonBuffer jsonBuffer;

           ^

C:\Users\User\Documents\Arduino\libraries\UniversalTelegramBot\src\UniversalTelegramBot.cpp:601:11: error: DynamicJsonBuffer is a class from ArduinoJson 5. Please see arduinojson.org/upgrade to learn how to upgrade your program to ArduinoJson version 6

   DynamicJsonBuffer keyboardBuffer;

           ^

C:\Users\User\Documents\Arduino\libraries\UniversalTelegramBot\src\UniversalTelegramBot.cpp:684:11: error: DynamicJsonBuffer is a class from ArduinoJson 5. Please see arduinojson.org/upgrade to learn how to upgrade your program to ArduinoJson version 6

   DynamicJsonBuffer jsonBuffer;

           ^

C:\Users\User\Documents\Arduino\libraries\UniversalTelegramBot\src\UniversalTelegramBot.cpp:705:11: error: DynamicJsonBuffer is a class from ArduinoJson 5. Please see arduinojson.org/upgrade to learn how to upgrade your program to ArduinoJson version 6

     DynamicJsonBuffer keyboardBuffer;

           ^

C:\Users\User\Documents\Arduino\libraries\UniversalTelegramBot\src\UniversalTelegramBot.cpp: In member function 'String UniversalTelegramBot::sendPostToTelegram(String, ArduinoJson::JsonObject&)':

C:\Users\User\Documents\Arduino\libraries\UniversalTelegramBot\src\UniversalTelegramBot.cpp:120:26: error: 'ArduinoJson::JsonObject {aka class ArduinoJson6120_000001::ObjectRef}' has no member named 'measureLength'

     int length = payload.measureLength();

                          ^

C:\Users\User\Documents\Arduino\libraries\UniversalTelegramBot\src\UniversalTelegramBot.cpp:128:13: error: 'ArduinoJson::JsonObject {aka class ArduinoJson6120_000001::ObjectRef}' has no member named 'printTo'

     payload.printTo(out);

             ^

C:\Users\User\Documents\Arduino\libraries\UniversalTelegramBot\src\UniversalTelegramBot.cpp: In member function 'bool UniversalTelegramBot::getMe()':

C:\Users\User\Documents\Arduino\libraries\UniversalTelegramBot\src\UniversalTelegramBot.cpp:319:21: error: 'jsonBuffer' was not declared in this scope

   DynamicJsonBuffer jsonBuffer;

                     ^

C:\Users\User\Documents\Arduino\libraries\UniversalTelegramBot\src\UniversalTelegramBot.cpp:324:12: error: 'ArduinoJson::JsonObject {aka class ArduinoJson6120_000001::ObjectRef}' has no member named 'success'

   if (root.success()) {

            ^

C:\Users\User\Documents\Arduino\libraries\UniversalTelegramBot\src\UniversalTelegramBot.cpp: In member function 'int UniversalTelegramBot::getUpdates(long int)':

C:\Users\User\Documents\Arduino\libraries\UniversalTelegramBot\src\UniversalTelegramBot.cpp:369:23: error: 'jsonBuffer' was not declared in this scope

     DynamicJsonBuffer jsonBuffer;

                       ^

C:\Users\User\Documents\Arduino\libraries\UniversalTelegramBot\src\UniversalTelegramBot.cpp:372:14: error: 'ArduinoJson::JsonObject {aka class ArduinoJson6120_000001::ObjectRef}' has no member named 'success'

     if (root.success()) {

              ^

C:\Users\User\Documents\Arduino\libraries\UniversalTelegramBot\src\UniversalTelegramBot.cpp:382:50: error: invalid initialization of non-const reference of type 'ArduinoJson::JsonObject& {aka ArduinoJson6120_000001::ObjectRef&}' from an rvalue of type 'ArduinoJson6120_000001::ObjectRef'

             JsonObject &result = root["result"][i];

                                                  ^

In file included from C:\Users\User\Documents\Arduino\libraries\ArduinoJson\src/ArduinoJson/Operators/VariantOperators.hpp:7:0,

                 from C:\Users\User\Documents\Arduino\libraries\ArduinoJson\src/ArduinoJson/Variant/VariantRef.hpp:12,

                 from C:\Users\User\Documents\Arduino\libraries\ArduinoJson\src/ArduinoJson/Array/ArrayIterator.hpp:8,

                 from C:\Users\User\Documents\Arduino\libraries\ArduinoJson\src/ArduinoJson/Array/ArrayRef.hpp:8,

                 from C:\Users\User\Documents\Arduino\libraries\ArduinoJson\src/ArduinoJson.hpp:17,

                 from C:\Users\User\Documents\Arduino\libraries\ArduinoJson\src/ArduinoJson.h:9,

                 from C:\Users\User\Documents\Arduino\libraries\UniversalTelegramBot\src\UniversalTelegramBot.h:26,

                 from C:\Users\User\Documents\Arduino\libraries\UniversalTelegramBot\src\UniversalTelegramBot.cpp:36:

C:\Users\User\Documents\Arduino\libraries\ArduinoJson\src/ArduinoJson/Operators/VariantCasts.hpp:15:16: note:   after user-defined conversion: ArduinoJson6120_000001::VariantCasts<TImpl>::operator T() const [with T = ArduinoJson6120_000001::ObjectRef; TImpl = ArduinoJson6120_000001::ElementProxy<const ArduinoJson6120_000001::MemberProxy<const ArduinoJson6120_000001::ObjectRef&, const char*>&>]

   FORCE_INLINE operator T() const {

                ^

C:\Users\User\Documents\Arduino\libraries\UniversalTelegramBot\src\UniversalTelegramBot.cpp: In member function 'bool UniversalTelegramBot::processResult(ArduinoJson::JsonObject&, int)':

C:\Users\User\Documents\Arduino\libraries\UniversalTelegramBot\src\UniversalTelegramBot.cpp:431:45: error: invalid initialization of non-const reference of type 'ArduinoJson::JsonObject& {aka ArduinoJson6120_000001::ObjectRef&}' from an rvalue of type 'ArduinoJson6120_000001::ObjectRef'

       JsonObject &message = result["message"];

                                             ^

In file included from C:\Users\User\Documents\Arduino\libraries\ArduinoJson\src/ArduinoJson/Operators/VariantOperators.hpp:7:0,

                 from C:\Users\User\Documents\Arduino\libraries\ArduinoJson\src/ArduinoJson/Variant/VariantRef.hpp:12,

                 from C:\Users\User\Documents\Arduino\libraries\ArduinoJson\src/ArduinoJson/Array/ArrayIterator.hpp:8,

                 from C:\Users\User\Documents\Arduino\libraries\ArduinoJson\src/ArduinoJson/Array/ArrayRef.hpp:8,

                 from C:\Users\User\Documents\Arduino\libraries\ArduinoJson\src/ArduinoJson.hpp:17,

                 from C:\Users\User\Documents\Arduino\libraries\ArduinoJson\src/ArduinoJson.h:9,

                 from C:\Users\User\Documents\Arduino\libraries\UniversalTelegramBot\src\UniversalTelegramBot.h:26,

                 from C:\Users\User\Documents\Arduino\libraries\UniversalTelegramBot\src\UniversalTelegramBot.cpp:36:

C:\Users\User\Documents\Arduino\libraries\ArduinoJson\src/ArduinoJson/Operators/VariantCasts.hpp:15:16: note:   after user-defined conversion: ArduinoJson6120_000001::VariantCasts<TImpl>::operator T() const [with T = ArduinoJson6120_000001::ObjectRef; TImpl = ArduinoJson6120_000001::MemberProxy<const ArduinoJson6120_000001::ObjectRef&, const char*>]

   FORCE_INLINE operator T() const {

                ^

C:\Users\User\Documents\Arduino\libraries\UniversalTelegramBot\src\UniversalTelegramBot.cpp:451:50: error: invalid initialization of non-const reference of type 'ArduinoJson::JsonObject& {aka ArduinoJson6120_000001::ObjectRef&}' from an rvalue of type 'ArduinoJson6120_000001::ObjectRef'

       JsonObject &message = result["channel_post"];

                                                  ^

In file included from C:\Users\User\Documents\Arduino\libraries\ArduinoJson\src/ArduinoJson/Operators/VariantOperators.hpp:7:0,

                 from C:\Users\User\Documents\Arduino\libraries\ArduinoJson\src/ArduinoJson/Variant/VariantRef.hpp:12,

                 from C:\Users\User\Documents\Arduino\libraries\ArduinoJson\src/ArduinoJson/Array/ArrayIterator.hpp:8,

                 from C:\Users\User\Documents\Arduino\libraries\ArduinoJson\src/ArduinoJson/Array/ArrayRef.hpp:8,

                 from C:\Users\User\Documents\Arduino\libraries\ArduinoJson\src/ArduinoJson.hpp:17,

                 from C:\Users\User\Documents\Arduino\libraries\ArduinoJson\src/ArduinoJson.h:9,

                 from C:\Users\User\Documents\Arduino\libraries\UniversalTelegramBot\src\UniversalTelegramBot.h:26,

                 from C:\Users\User\Documents\Arduino\libraries\UniversalTelegramBot\src\UniversalTelegramBot.cpp:36:

C:\Users\User\Documents\Arduino\libraries\ArduinoJson\src/ArduinoJson/Operators/VariantCasts.hpp:15:16: note:   after user-defined conversion: ArduinoJson6120_000001::VariantCasts<TImpl>::operator T() const [with T = ArduinoJson6120_000001::ObjectRef; TImpl = ArduinoJson6120_000001::MemberProxy<const ArduinoJson6120_000001::ObjectRef&, const char*>]

   FORCE_INLINE operator T() const {

                ^

C:\Users\User\Documents\Arduino\libraries\UniversalTelegramBot\src\UniversalTelegramBot.cpp:460:52: error: invalid initialization of non-const reference of type 'ArduinoJson::JsonObject& {aka ArduinoJson6120_000001::ObjectRef&}' from an rvalue of type 'ArduinoJson6120_000001::ObjectRef'

       JsonObject &message = result["callback_query"];

                                                    ^

In file included from C:\Users\User\Documents\Arduino\libraries\ArduinoJson\src/ArduinoJson/Operators/VariantOperators.hpp:7:0,

                 from C:\Users\User\Documents\Arduino\libraries\ArduinoJson\src/ArduinoJson/Variant/VariantRef.hpp:12,

                 from C:\Users\User\Documents\Arduino\libraries\ArduinoJson\src/ArduinoJson/Array/ArrayIterator.hpp:8,

                 from C:\Users\User\Documents\Arduino\libraries\ArduinoJson\src/ArduinoJson/Array/ArrayRef.hpp:8,

                 from C:\Users\User\Documents\Arduino\libraries\ArduinoJson\src/ArduinoJson.hpp:17,

                 from C:\Users\User\Documents\Arduino\libraries\ArduinoJson\src/ArduinoJson.h:9,

                 from C:\Users\User\Documents\Arduino\libraries\UniversalTelegramBot\src\UniversalTelegramBot.h:26,

                 from C:\Users\User\Documents\Arduino\libraries\UniversalTelegramBot\src\UniversalTelegramBot.cpp:36:

C:\Users\User\Documents\Arduino\libraries\ArduinoJson\src/ArduinoJson/Operators/VariantCasts.hpp:15:16: note:   after user-defined conversion: ArduinoJson6120_000001::VariantCasts<TImpl>::operator T() const [with T = ArduinoJson6120_000001::ObjectRef; TImpl = ArduinoJson6120_000001::MemberProxy<const ArduinoJson6120_000001::ObjectRef&, const char*>]

   FORCE_INLINE operator T() const {

                ^

C:\Users\User\Documents\Arduino\libraries\UniversalTelegramBot\src\UniversalTelegramBot.cpp:472:52: error: invalid initialization of non-const reference of type 'ArduinoJson::JsonObject& {aka ArduinoJson6120_000001::ObjectRef&}' from an rvalue of type 'ArduinoJson6120_000001::ObjectRef'

       JsonObject &message = result["edited_message"];

                                                    ^

In file included from C:\Users\User\Documents\Arduino\libraries\ArduinoJson\src/ArduinoJson/Operators/VariantOperators.hpp:7:0,

                 from C:\Users\User\Documents\Arduino\libraries\ArduinoJson\src/ArduinoJson/Variant/VariantRef.hpp:12,

                 from C:\Users\User\Documents\Arduino\libraries\ArduinoJson\src/ArduinoJson/Array/ArrayIterator.hpp:8,

                 from C:\Users\User\Documents\Arduino\libraries\ArduinoJson\src/ArduinoJson/Array/ArrayRef.hpp:8,

                 from C:\Users\User\Documents\Arduino\libraries\ArduinoJson\src/ArduinoJson.hpp:17,

                 from C:\Users\User\Documents\Arduino\libraries\ArduinoJson\src/ArduinoJson.h:9,

                 from C:\Users\User\Documents\Arduino\libraries\UniversalTelegramBot\src\UniversalTelegramBot.h:26,

                 from C:\Users\User\Documents\Arduino\libraries\UniversalTelegramBot\src\UniversalTelegramBot.cpp:36:

C:\Users\User\Documents\Arduino\libraries\ArduinoJson\src/ArduinoJson/Operators/VariantCasts.hpp:15:16: note:   after user-defined conversion: ArduinoJson6120_000001::VariantCasts<TImpl>::operator T() const [with T = ArduinoJson6120_000001::ObjectRef; TImpl = ArduinoJson6120_000001::MemberProxy<const ArduinoJson6120_000001::ObjectRef&, const char*>]

   FORCE_INLINE operator T() const {

                ^

C:\Users\User\Documents\Arduino\libraries\UniversalTelegramBot\src\UniversalTelegramBot.cpp: In member function 'bool UniversalTelegramBot::sendMessage(String, String, String)':

C:\Users\User\Documents\Arduino\libraries\UniversalTelegramBot\src\UniversalTelegramBot.cpp:530:21: error: 'jsonBuffer' was not declared in this scope

   DynamicJsonBuffer jsonBuffer;

                     ^

C:\Users\User\Documents\Arduino\libraries\UniversalTelegramBot\src\UniversalTelegramBot.cpp: In member function 'bool UniversalTelegramBot::sendMessageWithReplyKeyboard(String, String, String, String, bool, bool, bool)':

C:\Users\User\Documents\Arduino\libraries\UniversalTelegramBot\src\UniversalTelegramBot.cpp:547:21: error: 'jsonBuffer' was not declared in this scope

   DynamicJsonBuffer jsonBuffer;

                     ^

C:\Users\User\Documents\Arduino\libraries\UniversalTelegramBot\src\UniversalTelegramBot.cpp:557:55: error: invalid initialization of non-const reference of type 'ArduinoJson::JsonObject& {aka ArduinoJson6120_000001::ObjectRef&}' from an rvalue of type 'ArduinoJson6120_000001::ObjectRef'

   JsonObject &replyMarkup = payload.createNestedObject("reply_markup");

                                                       ^

C:\Users\User\Documents\Arduino\libraries\UniversalTelegramBot\src\UniversalTelegramBot.cpp:564:21: error: 'keyboardBuffer' was not declared in this scope

   DynamicJsonBuffer keyboardBuffer;

                     ^

C:\Users\User\Documents\Arduino\libraries\UniversalTelegramBot\src\UniversalTelegramBot.cpp: In member function 'bool UniversalTelegramBot::sendMessageWithInlineKeyboard(String, String, String, String)':

C:\Users\User\Documents\Arduino\libraries\UniversalTelegramBot\src\UniversalTelegramBot.cpp:589:21: error: 'jsonBuffer' was not declared in this scope

   DynamicJsonBuffer jsonBuffer;

                     ^

C:\Users\User\Documents\Arduino\libraries\UniversalTelegramBot\src\UniversalTelegramBot.cpp:599:55: error: invalid initialization of non-const reference of type 'ArduinoJson::JsonObject& {aka ArduinoJson6120_000001::ObjectRef&}' from an rvalue of type 'ArduinoJson6120_000001::ObjectRef'

   JsonObject &replyMarkup = payload.createNestedObject("reply_markup");

                                                       ^

C:\Users\User\Documents\Arduino\libraries\UniversalTelegramBot\src\UniversalTelegramBot.cpp:601:21: error: 'keyboardBuffer' was not declared in this scope

   DynamicJsonBuffer keyboardBuffer;

                     ^

C:\Users\User\Documents\Arduino\libraries\UniversalTelegramBot\src\UniversalTelegramBot.cpp: In member function 'String UniversalTelegramBot::sendPhoto(String, String, String, bool, int, String)':

C:\Users\User\Documents\Arduino\libraries\UniversalTelegramBot\src\UniversalTelegramBot.cpp:684:21: error: 'jsonBuffer' was not declared in this scope

   DynamicJsonBuffer jsonBuffer;

                     ^

C:\Users\User\Documents\Arduino\libraries\UniversalTelegramBot\src\UniversalTelegramBot.cpp:703:57: error: invalid initialization of non-const reference of type 'ArduinoJson::JsonObject& {aka ArduinoJson6120_000001::ObjectRef&}' from an rvalue of type 'ArduinoJson6120_000001::ObjectRef'

     JsonObject &replyMarkup = payload.createNestedObject("reply_markup");

                                                         ^

C:\Users\User\Documents\Arduino\libraries\UniversalTelegramBot\src\UniversalTelegramBot.cpp:705:23: error: 'keyboardBuffer' was not declared in this scope

     DynamicJsonBuffer keyboardBuffer;

                       ^

Multiple libraries were found for "WiFi.h"
 Used: C:\Users\User\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.4\libraries\WiFi
 Not used: C:\Program
exit status 1
Error compiling for board WEMOS LOLIN32.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by witnessmenow** [comment]
Update to the latest version of this library on github
