### ISSUE TITLE
Receive messages from group?

### ISSUE THREAD

**Issue by fmarzocca** [witnessmenow/Universal-Arduino-Telegram-Bot#141]
I have made a group with myself and my Bot, where it sends notifications. It would be great if this library could receive my messages directly from the channel, otherwise I have to send a message to the Bot and receive the notification in the group.

**Comment by witnessmenow** [comment]
The library can receive messages from a group, maybe your bots settings
aren't right?

In the botfather you can turn off group privacy for a bots, which allows
them see messages in groups as far as I know

**Comment by fmarzocca** [comment]
Thanks for answering. I was thinking at something that avoids reducing group privacy...

**Comment by fmarzocca** [comment]
I got it by sending commands with leading "/" symbol.
