### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by TheNitek** [witnessmenow/Universal-Arduino-Telegram-Bot#146]
The License File state that this lib is under GPL2 while the Readme references LGPL3. Could you please clarify which one is the current license?

**Comment by cxcorp** [comment]
The files under `src/` also have the LGPL-2.1 preamble:

> This library is free software; you can redistribute it and/or
> modify it under the terms of the GNU Lesser General Public
> License as published by the Free Software Foundation; either
> version 2.1 of the License, or (at your option) any later version.

**Comment by witnessmenow** [comment]
License has been updated to MIT in current Master
