### ISSUE TITLE
Sent Message Status

### ISSUE THREAD

**Issue by DimChik2903** [witnessmenow/Universal-Arduino-Telegram-Bot#154]
Can I somehow get the status of the messages I'm trying to send? It’s important for me to know if it has succeeded. If not, it is important to know the error number. For what reason the message was not sent. Thank you in advance!

**Comment by witnessmenow** [comment]
Most of the sendMessage commands return a boolean status, where true means it was successful.

It doesn't currently support what reason it returns false though.
