### ISSUE TITLE
ESP8266 examples is not working anymore

### ISSUE THREAD

**Issue by fabricioncosta** [witnessmenow/Universal-Arduino-Telegram-Bot#156]
Hi,

The ESP8266 examples are not working anymore. The ESP32 example still working. In orther to fix it, you can call client.setInsecure() after initialize the WiFiClientSecure object.

Regards,

**Comment by MaitrePo** [comment]
Hello,
I'm not sure to understand, it appears that the WiFiClientSecureObject doesn't have a "setInsecure()" method...?

Regards,

**Comment by fabricioncosta** [comment]
Hi,

Yes. That is it!

Regards,

Fabricio 

Fabrício

**Comment by witnessmenow** [comment]
Fixed on master branch
