### ISSUE TITLE
esp8266 examles are not woring anymore

### ISSUE THREAD

**Issue by 555learnwithme555** [witnessmenow/Universal-Arduino-Telegram-Bot#163]
non of the examples are working even after downgrading the board version to 2.5.2 and also tried adding client.setInsecure()......... hoping someone would help me finding a solution...

**Comment by MaitrePo** [comment]
Where did you add client.setInsecure() ?

**Comment by 555learnwithme555** [comment]
i added it in void setup

**Comment by MaitrePo** [comment]
Which example did you try ? I added client.setInsecure() at the end of the setup() method.
I added some logs with Serial.println() in my program.
I also set to "true" the "debug" variable in UniversalTelegramBot.h (in Arduino\libraries\Universal-Arduino-Telegram-Bot-master\src) .
Maybe this would help you to be sure that there is not any other problem ?

**Comment by ShrileshKale** [comment]
@MaitrePo 
I did what you said above but no success. 

- board version -2.5.2

- Code - Picked up from sample code (e.g Flash led)

- Added client.setInsecure() in void.setup()

![image](https://user-images.githubusercontent.com/13320662/80839472-991ba780-8bfb-11ea-907d-c56097704b06.png)

I am not getting any output after this..Could you please help me?

**Comment by prontodos** [comment]
Same for me but it starting working well after I added this line below the void setup() 

client.setInsecure();

**Comment by ShrileshKale** [comment]
Ok.what is your Arduino IDE and ESP8266 board version?

**Comment by prontodos** [comment]
esp8266 (now) 2.7.0
2.6.3 worked as well but I read here that 2.5.x are are stable. 

arduino ide 1.8.12

good luck

**Comment by ShrileshKale** [comment]
@prontodos No success with 2.7 , 2.6.3. What to do now?

**Comment by sicamxdf** [comment]
the examples for flash led does not work always have the same response {"ok":false,"error_code":401,"description":"Unauthorized"}

esp8266 (now) 2.7.0
arduino ide 1.8.12
thanks in advance

**Comment by witnessmenow** [comment]
Examples have all been updated on master branch. Will be released soon, but for now use the Github version of the library.
