### ISSUE TITLE
No issue, but is a question it's possible load token information from SPIFFS using ArduinoJson file?

### ISSUE THREAD

**Issue by javierferwolf** [witnessmenow/Universal-Arduino-Telegram-Bot#167]
Hello everyone, please any information or code example would be very helpful! I need load token information from SPIFFS using ArduinoJson file....!
thank you!

**Comment by witnessmenow** [comment]
This example kind of shows what you need to do from this library point of view, although it would need to be updated for SPIFFS

https://github.com/witnessmenow/Universal-Arduino-Telegram-Bot/blob/fa07c6abf3165968a833e629eb718b61c38751bc/examples/UntestedSinceUpgrade/ESP8266/UsingWiFiManager/UsingWiFiManager.ino
