### ISSUE TITLE
Bot can't receive messages

### ISSUE THREAD

**Issue by sandroxGH** [witnessmenow/Universal-Arduino-Telegram-Bot#177]
For the handler i receive this message
[E][WiFiGeneric.cpp:654] hostByName(): DNS Failed for api.telegram.org
[E][WiFiClientSecure.cpp:132] connect(): start_ssl_client: -1
[E][ssl_client.cpp:36] _handle_error(): [data_to_read():273]: (-80) UNKNOWN ERROR CODE (0050)

**Comment by phschoen** [comment]
i have the same issue. with an esp8266 its not working. even the basic EchoBot example is not working.
However with the example of an esp32 with the EchoBot is working correctly.

**Comment by sandroxGH** [comment]
I've solved enabling the Bot to chat in the group. Im my case the bot is a
remote control for some stuff and is working in a chat group of user.
After enabling it in the bot father  and wait some hours  it start work
like usual.
Regards

Il giorno lun 8 giu 2020 alle ore 18:57 Philipp Schönberger <
notifications@github.com> ha scritto:

**Comment by sandroxGH** [comment]
I've solved enabling the Bot to chat in the group. Im my case the bot is a remote control for some stuff and is working in a chat group of user.

**Comment by Europaco** [comment]
Hy‼️

I have that same problem:

[WiFiGeneric.cpp:654] hostByName(): DNS Failed for api.telegram.org

[WiFiClientSecure.cpp:132] connect(): start_ssl_client: -1

What do you mean by enabling it in the botFather?
What command do you use in the father bot to reactivate?
