### ISSUE TITLE
Json library version 6.x

### ISSUE THREAD

**Issue by mrWheel** [witnessmenow/Universal-Arduino-Telegram-Bot#179]
Is there any change in the near future that you will upgrade this library to use the json 6.x library?

**Comment by witnessmenow** [comment]
The v1.2 branch has this change, a new release will be coming soon

**Comment by witnessmenow** [comment]
Master branch has this too, still needs some more testing before releasing to Arduino Library manager though

**Comment by witnessmenow** [comment]
Prepping for V1.2 now, will be released soon
