### ISSUE TITLE
Library's compatibility with Ethernet adapters 

### ISSUE THREAD

**Issue by Roberto6969** [witnessmenow/Universal-Arduino-Telegram-Bot#188]
Hello!

Thank you for the great library!
Library works great with ESP32. But if i connect Ethernet adapter W5500 to ESP32, messages stops to flow. Ethernet communication still goes on. Maybe this is not an issue and it is based on design of library. Is use of Ethernet adapter with this library possible at all? I would like to use this library with wired Ethernet with ESP or with Mega 2560.

Thank You!

**Comment by witnessmenow** [comment]
This library should work with any client that supports HTTPS and TLS V1.2

I'm open to correction, but I do not believe any of the Ethernet adapters available meet that requirement
