### ISSUE TITLE
bot.getUpdates() always returns 0 with ESP32

### ISSUE THREAD

**Issue by careyer** [witnessmenow/Universal-Arduino-Telegram-Bot#195]
Thank you very much for this awesome project. 
I am experiencing a similar problem to #121 but this time on ESP32. Every call of `bot.getUpdates()` just returns 0 even though there are new messages for the bot.

Appearantly the bot integration works though because I can use the `bot.sendMessage()` command to successfully send messages to the chat, i.e. my WiFi connection and Bot API-key and chat_ID are correct.

Sadly for ESP32 there is no `client.setInsecure()` for `WiFiClientSecure client`;
Any idea how to solve this? Any help is much appreaciated.

Thanks and keep up the good work!
Best regards

**Comment by witnessmenow** [comment]
Hmm, confusing one!

First thing I would try is to use a different bot, just in case your current one is in use somewhere else. (This would only impact reading messages, not sending)

Are you talking to the bot in a group or directly?

**Comment by careyer** [comment]
@witnessmenow Hey Brian, thanks for comming back to me! I tried with another bot now and indeed the problem is gone now. Thanks for your help!!!
