### ISSUE TITLE
Make BOT_TOKEN changeble

### ISSUE THREAD

**Issue by jowiemann** [witnessmenow/Universal-Arduino-Telegram-Bot#197]
Hello,

with a little change it would be possible to chnage bot token via runtime:

**UniversalTelegramBot.h**
UniversalTelegramBot(Client &client);
void setTelegramBotToken(String token);

**UniversalTelegramBot.cpp**
UniversalTelegramBot::UniversalTelegramBot(Client &client) {
  _token = "";
  this->client = &client;
}

void UniversalTelegramBot::setTelegramBotToken(String token) {
  _token = token;
}

Thank you

**Comment by jamesmyatt** [comment]
There's an updateToken method. Does that work?

**Comment by witnessmenow** [comment]
as mentioned by @jamesmyatt , updateToken is exactly what you are looking for

https://github.com/witnessmenow/Universal-Arduino-Telegram-Bot/blob/master/src/UniversalTelegramBot.cpp#L46
