### ISSUE TITLE
Create a public Telegram group for users of the library

### ISSUE THREAD

**Issue by witnessmenow** [witnessmenow/Universal-Arduino-Telegram-Bot#21]
It might be helpful to help each other via Telegram, we are obviously all users of it!

**Comment by rusboard** [comment]
Try to create it. We will try to join there :)

**Comment by rusboard** [comment]
@universal_arduino_telegram_bot
https://telegram.me/universal_arduino_telegram_bot

Something like this?

**Comment by rusboard** [comment]
Universal Arduino Telegram Bot library logo (ver 0.01) created too for channel :)

**Comment by rusboard** [comment]
Group is removed. You can create your own group with same username and url and you will be as creator there.

**Comment by rusboard** [comment]
I already have couple question. How to fork send_image branch, can't understand.

**Comment by witnessmenow** [comment]
Created now, I used a shorter name to make it easier to share

http://t.me/arduino_library

**Comment by witnessmenow** [comment]
New URL https://t.me/arduino_telegram_library
