### ISSUE TITLE
load BOT_TOKEN

### ISSUE THREAD

**Issue by workpage2** [witnessmenow/Universal-Arduino-Telegram-Bot#221]
I load the BOT_TOKEN value from the eeprom into the setup of my sketch. But I have to set the BOT_TOKEN value BEFORE executing the program. How can I set BOT_TOKEN in the program itself or change it?

    #define BOT_TOKEN "XXXXXXXXX:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
    WiFiClientSecure secured_client;
    UniversalTelegramBot bot(BOT_TOKEN, secured_client);

**Comment by witnessmenow** [comment]
There is an update token method

https://github.com/witnessmenow/Universal-Arduino-Telegram-Bot/blob/master/src/UniversalTelegramBot.h#L71
