### ISSUE TITLE
Multiple users with multiple devices with a single Bot(token) question

### ISSUE THREAD

**Issue by garudaonekh** [witnessmenow/Universal-Arduino-Telegram-Bot#256]
Hi,
My purpose is to have multiple users using the same Bot(same token) and devices are assigned to different chat_id(users) rather than 1 device one Bot. This is too tedious.

I want to use the same token to manage 20+ esp8266 relay.
But it shows conflict error in getUpdates().
`  "error_code": 409,
  "description": "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"`

Is there any way to filter update based on chat_id(user_id)?

Thanks;

**Comment by witnessmenow** [comment]
That's a telegram error. There is no way to filter by chat Id without reading the message, which would still have the same problem your seeing here.

Sorry, I don't have any suggestions here
