### ISSUE TITLE
How to forget messages after x-Seconds/Minutes?

### ISSUE THREAD

**Issue by petergeher** [witnessmenow/Universal-Arduino-Telegram-Bot#267]
Hi, 

Everything works fine in the meantime. However a small problem: If the esp8266 times is not attainable and I want to switch on a relay with /on, and send the message several times, it is done after again reach several times. 

Is there a solution? 

Best regards,
Peter

**Comment by witnessmenow** [comment]
I don't think i have anything in the library that could help with that. I
guess it should in theory be possible to see when the message was sent and
ignore it if its old, but I don't think I parse anything like that
