### ISSUE TITLE
Send message with menu

### ISSUE THREAD

**Issue by joroMaser** [witnessmenow/Universal-Arduino-Telegram-Bot#271]
How can I send with this great library message that include menu like

https://i.stack.imgur.com/1NlYr.png

**Comment by SebouhArmenakian** [comment]
From Example use the Custom Keyboard and assign a button to send a message

**Comment by joroMaser** [comment]
@SebouhArmenakian Ok , I saw
https://github.com/witnessmenow/Universal-Arduino-Telegram-Bot/blob/master/examples/ESP8266/CustomKeyboard/InlineKeyboardMarkup/InlineKeyboardMarkup.ino#L50
That great , but How can I handle callback_data ???

Thank you!
