### ISSUE TITLE
Method 'as' could not be resolved

### ISSUE THREAD

**Issue by jenya7** [witnessmenow/Universal-Arduino-Telegram-Bot#309]
I include the library in my project and get a lot of errors
**Method 'as' could not be resolved**

Here for example
`
messages[messageIndex].from_id = message["from"]["id"].as<String>();
messages[messageIndex].from_name = message["from"]["first_name"].as<String>();
`

**Comment by witnessmenow** [comment]
Using wrong version of Arduino JSON?
