### ISSUE TITLE
Can a bot make a call?

### ISSUE THREAD

**Issue by Barabba11** [witnessmenow/Universal-Arduino-Telegram-Bot#312]
Hi mates, sorry to open an issue to ask this but I consider it an important request. 
I need to be adviced by phone suddenly, and messages aren't able to warn me in the same way a call do, can bot produce a telegram call?
If not, do I have chance in telegram to set for a specific contact long vibration and long ringtone? In this case I have to create a second bot, because I also want to receive non-crytical messages, about status and so on, which should be notified silently. 
Thank you for your kind opinions

**Comment by witnessmenow** [comment]
I don't know if it can, but this library definitely doesn't support it

Sorry I also don't know about setting specific tones for individial users, sorry!
