### ISSUE TITLE
Support the additional inline Keyboard types

### ISSUE THREAD

**Issue by witnessmenow** [witnessmenow/Universal-Arduino-Telegram-Bot#34]
Currently inline keyboard only supports URLs, additional work is needed to handle callbacks

**Comment by prassaschr** [comment]
Kindly requesting the "callback button" type.
Thank you!

**Comment by witnessmenow** [comment]
I won't get to make any changes to the library for a few weeks at least. I don't think there would be a lot of changes needed, the getUpdates message will need to support the callback.

I created a branch to do some work on the getUpdates to support channel posts, I guess that would be a good starting point.

https://github.com/witnessmenow/Universal-Arduino-Telegram-Bot/blob/Channel_Post/src/UniversalTelegramBot.cpp#L338

I think if that is modified to check for CallbackQuery you should be able to parse whatever is needed from there

`else if (result.containsKey("callback_query")) { `

[It should contain the following fields](https://core.telegram.org/bots/api#callbackquery)

If you wanted to try it out that would be great!

**Comment by witnessmenow** [comment]
See #37 for more info on that branch

**Comment by witnessmenow** [comment]
Available in the V1.1.0 RC branch

https://github.com/witnessmenow/Universal-Arduino-Telegram-Bot/tree/V1.1.0
