### ISSUE TITLE
Send Image from SPIFF

### ISSUE THREAD

**Issue by ghost** [witnessmenow/Universal-Arduino-Telegram-Bot#47]
Hi,

Can you add an example how to send an Image from SPIFF?
Let's say I have a picture on the storage of my ESP8266 in /picture/1.jpg and I like to send this one.
Keep in mind this is different from the PhotoFromSD example.

Regards

**Comment by witnessmenow** [comment]
What have your tried so far?

As far as I can see if you add the correct headers for using SPIFF, you then only need to replace line 74 of the example with something like 

File f = SPIFFS.open("/picture/1.jpg", "r");

**Comment by witnessmenow** [comment]
No updates, closing
