### ISSUE TITLE
Nothing happens

### ISSUE THREAD

**Issue by pauk163rus** [witnessmenow/Universal-Arduino-Telegram-Bot#49]
Hi all! 
I'm use Arduino UNO R3 with Ethernet Shield W5100. Here is the code:

`
#include <ArduinoJson.h>
#include <UniversalTelegramBot.h>
#include <Ethernet.h>
#include <SPI.h>

// Initialize Telegram BOT

#define BOTtoken  "123456789:abcdefghijklmnopABCDEFGHIJKLMNOPxxx"

//const char* BotName = ""; // ---- what is it?
//const char* BotUsername = ""; // ----  what is it?

byte mac[] = { 0xDE, 0xAD, 0xBE, 0xEF, 0xFE, 0xED };
EthernetClient client;

int Bot_mtbs = 1000; //mean time between scan messages
long Bot_lasttime;   //last time messages' scan has been done
UniversalTelegramBot bot(BOTtoken, client);

void setup() {
  Serial.begin(9600);
  Ethernet.begin(mac);
  Serial.println (Ethernet.localIP());
 }

void loop() {

 
    int numNewMessages = bot.getUpdates(bot.last_message_received + 1);
    while(numNewMessages) {
      Serial.println("got response");
      for(int i=0; i<numNewMessages; i++) {
        bot.sendMessage(bot.messages[i].chat_id, bot.messages[i].text, "");
      }
      numNewMessages = bot.getUpdates(bot.last_message_received + 1);
    }
    Bot_lasttime = millis();
delay(1000);
}`

In serial port monitor, I see my Arduino gets the IP address, and after that - nothing ...

Help me please, if somebody can)))

**Comment by witnessmenow** [comment]
@pauk163rus Library is not supported by the ethernet shield as it can not do HTTPS
