### ISSUE TITLE
WiFiClientSecure can not connect

### ISSUE THREAD

**Issue by jratenci** [witnessmenow/Universal-Arduino-Telegram-Bot#59]
hi, 
i have a issue with the connection,  
in UniversalTelegramBot::sendGetToTelegram sometimes client->connect(HOST, SSL_PORT) return 0,
that mean  client could not connect to server. 
At the beginning it works well, but after a while the connection is lost.
this is my code in loop function 

int Bot_mtbs = 3500;
void loop() {
  if (millis() > Bot_lasttime + Bot_mtbs)  {
    int numNewMessages = bot.getUpdates(bot.last_message_received + 1);

    while(numNewMessages) {
      Serial.println("got response");
      for (int i=0; i<numNewMessages; i++) {
        bot.sendMessage(bot.messages[i].chat_id, bot.messages[i].text, "");
      }
      numNewMessages = bot.getUpdates(bot.last_message_received + 1);
    }

    Bot_lasttime = millis();
  }
}

**Comment by witnessmenow** [comment]
This isn't really something that can be fixed in the Telegram library. Version 2.4 of ESP8266 core seems to have fixed some issues around connected to servers so might be worth updating to that
