### ISSUE TITLE
Error in Echobot, WiFi.begin uses pass instead of password

### ISSUE THREAD

**Issue by zoomx** [witnessmenow/Universal-Arduino-Telegram-Bot#6]
Hello,
example EchoBot has a mismatch error.

line
while (WiFi.begin(ssid, pass) != WL_CONNECTED) {
must be
while (WiFi.begin(ssid, password) != WL_CONNECTED) {

or you have to change the declaration char password[] in char pass[]

**Comment by witnessmenow** [comment]
Hey @zoomx. I've pushed a new version there with a fix for that issue.

Thanks for the report! Please let me know if there is anything else I can help with
