### ISSUE TITLE
How to tell if bot is valid

### ISSUE THREAD

**Issue by AcuarioCat** [witnessmenow/Universal-Arduino-Telegram-Bot#61]
Hi,
is there a way to know that the bot is valid when it is created?
I would like to know that the token is valid and that I have a valid bot that I can use and if not then prompt for a valid token.
Thanks.

**Comment by witnessmenow** [comment]
Hi,

The easiest way is probably to use bot.getMe(); this will return true if
everything worked OK and will return false if it didn't (although it could
have failed for other reasons than your not token, internet connection for
example)

**Comment by AcuarioCat** [comment]
Thanks, as you say not perfect but it is the best solution available. Thanks.

**Comment by burdeyniyua** [comment]
I use next solution:
```
if (text == "ping) {
bot.sendMessage(chat_id, "I am Alive!", "Markdown");                          
  }
```
