### ISSUE TITLE
Conflict: can't use getUpdates method while webhook is active

### ISSUE THREAD

**Issue by patrickelectric** [witnessmenow/Universal-Arduino-Telegram-Bot#72]
```bash
api.telegram.org
443
.... connected to server

{"ok":false,"error_code":409,"description":"Conflict: can't use getUpdates method while webhook is active"}

incoming message length107
Creating DynamicJsonBuffer

Response contained no 'result'
```

**Comment by witnessmenow** [comment]
Hmm interesting. What would you expect to happen in this case?

**Comment by patrickelectric** [comment]
I'm running all esp8266 examples and none is working.

**Comment by witnessmenow** [comment]
Your must be used somewhere else that is using webhooks? Create a new bot or regenerate the token for it

**Comment by witnessmenow** [comment]
Correction cause i cant edit on mobile: Your bot token must be used somewhere else that is using webhooks? Create a new bot or regenerate the token for it

**Comment by patrickelectric** [comment]
Using a fresh one works.. ty !
Do you know what this ? My old bot is not running.

**Comment by witnessmenow** [comment]
I've never used web hook but maybe it still active even when the bot is not
running. I think if you generate a new token for that bot it should work
again
